### ISSUE TITLE
A tutorial to demonstrate the basic customization workflow

### ISSUE THREAD

**Issue by zcha621** [liris-xr/PLUME-Recorder#2]
I feel there is a need to create a tutorial to demonstrate the basic workflow for users who want to customize their recording and replay process.

A sample Unity scene will help users understand how the PLUME works on the Unity side.

Moreover, people like me who are not familiar with Protos, have no idea of how to customize our own Protos and how to use the generated C# file in Unity.

**Comment by cjaverliat** [comment]
Hello.
Yes, you are right, PLUME is lacking some good documentation at the moment due to a strong focus on the technical side for the publication. I will now be able to work on it.

Regarding proto files, a small example is given [here](https://github.com/liris-xr/PLUME-Recorder?tab=readme-ov-file#custom-sample). You can have a look on how to build a .proto file [here](https://github.com/liris-xr/PLUME-Protos?tab=readme-ov-file#getting-started) or more generally on the Google documentation.

Expect some updates in the next few weeks with better documentation. In the meantime, I invite you to join the [Discord Server](https://discord.com/invite/c3evqEWMge).

**Comment by zcha621** [comment]
Thanks so much.
I am looking forward to your cool demos and documentation.

**Comment by cjaverliat** [comment]
Hi @cz2011301070,
We just released the first version of the documentation. You can find a tutorial on how to record custom data here https://liris-xr.github.io/PLUME/recorder/advanced/recording-custom-data/
